const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');

const oldStr = `      const mandatorySuffix = \`\\n\\n=== ABSOLUTE CRITICAL CONSTRAINTS (MANDATORY) ===
- EXACT VISUAL CLONE OF DESIGN REFERENCE: You MUST perfectly trace and clone the exact shapes, layout grids, panel structures, background gradients, textures, and geometric dimensions of the provided Design Layout Reference. Do NOT invent new shapes, structures, or change the composition grid. It must look 100% identical in layout and structural design, simply applying the new text, logos, and colors.
- TEXT REPLACEMENT (CRITICAL): Do NOT copy the text, social media handles, or names from the Design Layout Reference image. You MUST ONLY use the text, @handles, and information explicitly provided in this prompt. Erase/replace any old text from the reference with the new requested text.
- COMPLETE CARD LAYOUT GENERATION: Do NOT generate just a plain empty background backdrop. You MUST generate the complete graphic composition, including all layouts, cards, panels, curved border divides, background textures, lighting setups, and the main visual subjects (e.g., joining hands, models, or products) in their exact spatial positions, proportions, and layouts as shown in the Design Layout Reference image.
- EMBEDDED TYPOGRAPHY (MANDATORY): You MUST print, write, embed, and render all actual written texts, titles, words, acronyms, letters, numbers, and website URLs directly onto the image canvas. Style them with beautiful, modern, extremely crisp, and highly-legible typography matching the alignments and visual style of the reference design. All social media usernames or handles (starting with "@") must be printed strictly in lowercase letters.
\${logoMandatoryRule}
- BRAND COLOR PALETTE ENFORCEMENT: If custom colors, hex codes (e.g. #ad8330), or light setup colors are specified in the prompt above, you MUST strictly use those exact colors for the entire graphic composition, background panels, highlights, glows, and ambient lighting, completely overriding the original reference flyer's colors.\`;`;

const newStr = `      const mandatorySuffix = \`\\n\\n=== ABSOLUTE CRITICAL CONSTRAINTS (MANDATORY) ===
- EXACT VISUAL CLONE OF DESIGN REFERENCE: You MUST perfectly trace and clone the exact shapes, layout grids, panel structures, background gradients, textures, and geometric dimensions of the provided Design Layout Reference. Do NOT invent new shapes, structures, or change the composition grid. It must look 100% identical in layout and structural design, simply applying the new text, logos, and colors.
- BRAND COLOR PALETTE ENFORCEMENT (CRITICAL): If custom colors, hex codes, or light setup colors are specified in the prompt above, you MUST strictly and aggressively use those EXACT colors for the entire graphic composition, background panels, highlights, glows, and ambient lighting. You MUST completely OVERRIDE the original reference flyer's colors with the requested colors. Do NOT use the reference colors if custom colors are provided!
- TEXT COMPLETENESS & PLACEMENT (CRITICAL): You MUST print ALL provided text fields, titles, and words exactly as requested. DO NOT SKIP ANY TEXT. You MUST place the text EXACTLY in the same spatial positions as the original text blocks found in the Design Layout Reference. DO NOT put text in random places. Replicate the original typographical hierarchy and alignment perfectly, but using the new text.
- COMPLETE CARD LAYOUT GENERATION: Do NOT generate just a plain empty background backdrop. You MUST generate the complete graphic composition, including all layouts, cards, panels, curved border divides, background textures, lighting setups, and the main visual subjects (e.g., joining hands, models, or products) in their exact spatial positions, proportions, and layouts as shown in the Design Layout Reference image.
- EMBEDDED TYPOGRAPHY (MANDATORY): You MUST print, write, embed, and render all actual written texts, titles, words, acronyms, letters, numbers, and website URLs directly onto the image canvas. Style them with beautiful, modern, extremely crisp, and highly-legible typography matching the alignments and visual style of the reference design. All social media usernames or handles (starting with "@") must be printed strictly in lowercase letters.
\${logoMandatoryRule}\`;`;

code = code.replace(oldStr, newStr);
fs.writeFileSync('server.ts', code);
